#!/bin/bash

MTU=$1

if [[ $MTU == "" ]]; then
  echo "usage: mtuset <mtu_value>"
  exit 1
fi

if (( MTU < 1500 || MTU > 9000)); then
  echo "Valid MTU sizes are 1500 - 9000"
  exit 1
fi
echo "Link MTUs before change"
ip link show | grep "eno49\|eno50"

ifconfig eno49 mtu $MTU up
ifconfig eno50 mtu $MTU up

echo "Link MTUs after change"
ip link show | grep "eno49\|eno50"
