services:
  kafka1:
    image: confluentinc/cp-kafka:latest
    hostname: kafka1
    container_name: kafka1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093"
      KAFKA_LISTENERS: "CONTROLLER://kafka1:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: "PLAIN"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "abcde"

  kafka2:
    image: confluentinc/cp-kafka:latest
    hostname: kafka2
    container_name: kafka2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka2:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: "PLAIN"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: "abcde"

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "8081:80"

  efu:
    image: registry.esss.lu.se/ecdc/ess-dmsc/event-formation-unit/efu-<instrument_name>:latest # e.g. dream
    hostname: efu
    container_name: efu
    depends_on:
      - kafka2
      - kafka1
      - graphite
    ports:
      - "9000:9000/udp"
      - "8888:8888/tcp"

    volumes:
      - /<essconfig_path>/essconfig/instruments/<instrument_name>/efu/config:/ess/ecdc/event_formation_unit/config/ # e.g. dream
    environment:
      - BROKER_TOPIC=<broker_topic> # e.g. dream_detector_mantle
      - FILE=<config_file_name> # e.g. 2024_06_06_1437_mantle.json
      # - CALIBRATION=cspecnullcalib.json
      - BROKER_ADDR=kafka2:9092
      - GRAPHITE=graphite


  daqlite:
    image: registry.esss.lu.se/ecdc/ess-dmsc/daqlite:1.0
    container_name: daqlite
    depends_on:
      - kafka2
      - kafka1
    ports:
      - "5902:5901"
    environment:
      - DAQLITE_BROKER=-b kafka2:9092
      - DAQLITE_PRODUCTION=true
      - VNC_PASSWORD=<vnc_password> # e.g. password

  akhq:
    image: tchiotludo/akhq:latest
    container_name: akhq
    depends_on:
      - kafka2
      - kafka1
    ports:
      - "8082:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka:
              properties:
                bootstrap.servers: "kafka2:9092"
                security.protocol: PLAINTEXT
                sasl.mechanism: PLAIN
    restart: always
