{
 "title": "EFU",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "region",
    "label": "region",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.count), 'readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.headers), 'headers/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.bytes), 'bytes/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.receive.fifo_seq_errors), 'fifo_seq err/s')"
    }
   ]
  },
  {
   "title": "ESS Header",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.version.v0), 'header v0/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.version.v1), 'header v1/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.error_buffer), 'buffer err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.error_cookie), 'cookie err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.error_header), 'header err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.error_pad), 'pad err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.error_seqno), 'deq err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.error_size), 'size err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.error_version), 'version err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.error_type), 'type err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.error_timehigh), 'timehigh err/s')"
    }
   ]
  },
  {
   "title": "Readouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.error_amplitude), 'ampl err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.count), 'readouts/s')"
    }
   ]
  },
  {
   "title": "Readout Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.error_amplitude), 'ampl err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.error_headersize), 'header size err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.error_datlen_invalid), 'datalen err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.error_ringfen), 'datalen err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.readouts.tof_high), 'tof high err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.essheader.version.v0), 'header v0/s')"
    }
   ]
  },
  {
   "title": "Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl.$region.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.kafka.produce_bytes_ok), 'bytes ok/s')"
    }
   ]
  },
  {
   "title": "Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "alias(perSecond(efu.tbl.$region.kafka.produce_bytes_ok), 'bytes ok/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.kafka.produce_bytes_error), 'bytes err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.kafka.err_unknown_topic), 'topic err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.kafka.err_queue_full), 'queue err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.kafka.produce_errors), 'produce err/s')"
    },
    {
     "target": "alias(perSecond(efu.tbl.$region.kafka.produce_no_errors), 'produce ok/s')"
    }
   ]
  }
 ]
}