{
 "title": "EFU",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instrument",
    "query": {}
   },
   {
    "name": "region",
    "label": "region",
    "query": {}
   },
   {
    "name": "producer",
    "label": "producer",
    "query": {}
   },
   {
    "name": "serializer",
    "label": "serializer",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "EFU Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(efu.$instrument.$region.main.uptime, 'uptime')"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(scale(perSecond(efu.$instrument.$region.thread.processing_idle), 0.00667), 'processing idle %')"
    },
    {
     "target": "alias(scale(perSecond(efu.$instrument.$region.thread.input_idle), 12.25), 'input idle %')"
    }
   ]
  },
  {
   "title": "Output Queue (OQ) Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.00.packets), 'OQ.00 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.01.packets), 'OQ.01 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.02.packets), 'OQ.02 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.03.packets), 'OQ.03 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.04.packets), 'OQ.04 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.05.packets), 'OQ.05 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.06.packets), 'OQ.06 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.07.packets), 'OQ.07 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.08.packets), 'OQ.08 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.09.packets), 'OQ.09 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.10.packets), 'OQ.10 packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.OQ.11.packets), 'OQ.11 packets/s')"
    }
   ]
  },
  {
   "title": "Receive Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.receive.packets), 'packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.receive.dropped), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(scale(efu.$instrument.$region.receive.bytes, 8)), 'bits/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.receive.fifo_seq_errors), 'seq err/s')"
    }
   ]
  },
  {
   "title": "ESS Readout Header Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.header), 'header errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.buffer), 'buffer errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.cookie), 'cookie errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.pad), 'padding errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.size), 'size errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.version), 'version errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.output_queue), 'OQ errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.type), 'type errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.seqno), 'seqno errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.timehigh), 'timehigh errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.errors.timefrac), 'timefrac errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.heartbeats), 'heartbeats/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.version.v0), 'v0 header/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.essheader.version.v1), 'v1 header/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.error_header), 'essheader error/s')"
    }
   ]
  },
  {
   "title": "Readout Data Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.count), 'readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.header.count), 'data headers/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.error_headersize), 'headersize errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.error_bytes), 'error bytes/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.error_ringfen), 'ring/fen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.error_datlen_invalid), 'datalen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.error_maxadc), 'maxadc err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.error_maxadc), 'maxadc err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.error_datlen_mismatch), 'datalen mismatch/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.count), 'readouts count/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.adc_max), 'adc max/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_mapping), 'readout mapping err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_fiber), 'fiber err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_fen), 'readout fen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_datalen), 'readout datalen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_timefrac), 'timefrac err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_bc), 'bc err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_adc), 'readout adc err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_vmm), 'vmm err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_channel), 'channel err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_size), 'readout size err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.data), 'readout data/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.bccalib), 'bccalib/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.tof_toolarge), 'tof too large/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_hybrid_mapping), 'hybrid mapping err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_ring_mapping), 'ring mapping err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_fen_mapping), 'fen mapping err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_invalid_xcoord), 'invalid x coord/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_invalid_ycoord), 'invalid y coord/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.errors.size), 'parser size err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.errors.fiber), 'parser fiber err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.errors.fen), 'parser fen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.errors.type), 'parser type err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.errors.adc), 'parser adc err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.errors.datalen), 'parser datalen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.errors.timefrac), 'parser timefrac err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parser.readout.errors.no_data), 'parser no data err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.errors.ring_mismatch), 'ring mismatch err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.errors.no_serializer), 'no serializer err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.errors.type_not_configured), 'type not config err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.errors.time), 'readout time err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.processed), 'readouts processed/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.type.event0d_proccessed), 'event0d processed/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.type.event2d_proccessed), 'event2d processed/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.type.ibm_processed), 'ibm processed/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.ibm_npos_sum), 'ibm npos sum/s')"
    }
   ]
  },
  {
   "title": "Geometry Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.ring_mapping_errors), 'ring mapping err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.fen_mapping_errors), 'fen mapping err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.calib_group_errors), 'calib errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.pos_low), 'clamp HI/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.pos_high), 'clamp LO/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.outside_tube), 'tube out/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.group_errors), 'group err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.topology_errors), 'topology err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.ring_errors), 'ring err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.fen_errors), 'fen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.ampl_zero), 'ampl zero/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.ampl_low), 'ampl low/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.geometry.ampl_high), 'ampl high/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.matched_clusters), 'matched clusters/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.no_coincidence), 'no coincidence/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.matched_x_only), 'matched x only/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.matched_y_only), 'matched y only/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.span.x_too_large), 'x span too large/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.span.y_too_large), 'y span too large/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.span.x_too_small), 'x span too small/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.span.y_too_small), 'y span too small/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.matcherstats.span_too_large), 'matcher span large/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.matcherstats.discared_span_too_large), 'discarded span large/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.matcherstats.split_span_too_large), 'split span large/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.matcherstats.match_attempt_count), 'match attempts/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.wire_only), 'wire only/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.cluster.strip_only), 'strip only/s')"
    }
   ]
  },
  {
   "title": "Event and Time rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.count), 'events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.errors.pixel), 'pixel errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.udder), 'udder events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.timestamp.tof.count), 'rToA/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.timestamp.tof.negative), 'rToA neg/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.timestamp.tof.high), 'rToA high/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.timestamp.prevtof.count), 'pre rToA/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.timestamp.prevtof.negative), 'pre rToA neg/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.timestamp.prevtof.high), 'pre rToA high/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.errors.time), 'time errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.strip_gaps), 'strip gaps/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.wire_gaps), 'wire gaps/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.ibm), 'ibm events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.event0d), 'event0d/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.event2d), 'event2d/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.tof_before_offset_dropped), 'tof before offset dropped/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.tof_over_max_dropped), 'tof over max dropped/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.tof_over_max_last_bin), 'tof over max last bin/s')"
    }
   ]
  },
  {
   "title": "EFU Producer Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.produce_calls), 'produce calls/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.produce_errors), 'produce errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.produce.cause.max_events_reached), 'produce max event/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.produce.cause.pulse_change), 'produce pulse time/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.produce.cause.timeout), 'produce timeout/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.stat_events), 'stat events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error_events), 'error events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_called), 'serialize produce called/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_triggered_reftime), 'produce triggered reftime/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_triggered_max_events), 'produce triggered max events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_failed_no_reftime), 'produce failed no reftime/s')"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "EFU Producer Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.produce_calls), 'produce calls/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.produce_errors), 'produce errors/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.produce.cause.max_events_reached), 'produce max event/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.produce.cause.pulse_change), 'produce pulse time/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.produce.cause.timeout), 'produce timeout/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.stat_events), 'stat events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error_events), 'error events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_called), 'serialize produce called/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_triggered_reftime), 'produce triggered reftime/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_triggered_max_events), 'produce triggered max events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_failed_no_reftime), 'produce failed no reftime/s')"
    }
   ]
  },
  {
   "title": "Kafka Msg Queue Status",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(efu.$instrument.$region.producer.$producer.msg.num_of_msg_in_queue, 'msg in queue')"
    }
   ]
  },
  {
   "title": "Kafka Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.authentication), 'auth err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.msg_delivery), 'msg delivery err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.msg_size), 'msg size err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.msg_timeout), 'msg timeout err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.queue_full), 'queue err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.timeout), 'timeout err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.transmission), 'transmission err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.transport), 'transport err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.unknown_partition), 'partition err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.unknown_topic), 'topic err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.other), 'other err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.config), 'config err/s')"
    }
   ]
  },
  {
   "title": "Kafka Msg Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.msg.delivery_success), 'delivery success/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.msg.status_persisted), 'msg persisted/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.produce_calls), 'produce calls/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.msg.msg_delivery_event), 'msg delivery event/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.msg.status_possibly_persisted), 'msg possibly persisted/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.msg.status_not_persisted), 'msg not persisted/s')"
    }
   ]
  },
  {
   "title": "Kafka Msg Queue Status History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(efu.$instrument.$region.producer.$producer.msg.bytes_of_msg_in_queue, 'current bytes in queue')"
    }
   ]
  },
  {
   "title": "Transmission to Kafka",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.brokers.tx_bytes), 'tx bytes/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.error.transmission), 'tx err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.brokers.tx_req_retries), 'tx retries/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.producer.$producer.produce_bytes_ok), 'produced bytes/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.produce.cause.monitor_packets), 'monitor pkts/s')"
    }
   ]
  }
 ]
}