networks:
  efu:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000

service:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - "8081:80"
    networks:
      - efu

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/var/lib/grafana/dashboards # Each dashboard is a json model file
    depends_on:
      - graphite
    restart: always
    networks:
      - efu

  efu:
    image: registry.esss.lu.se/ecdc/ess-dmsc/event-formation-unit/efu-tbl3he:latest
    hostname: efu-tbl3he
    container_name: efu-tbl3he
    depends_on:
      - graphite
    ports:
      - "9000:9000/udp"
      - "8888:8888/tcp"
    networks:
      - efu

    volumes:
      - /home/essdaq/kafka-config/staging_kafka.crt:/ess/ecdc/ssl/ecdc-kafka-ca.crt
      - /home/essdaq/kafka-config/kafka-config-staging.json:/ess/ecdc/kafka-config-staging.json
    # Required to mount the configuration and calibration to the container
    # Replace <essconfig_path> with the path to your locel essconfig directory
      - ${ESSCONFIG_PATH}/instruments/tbl/efu/config:/ess/ecdc/event_formation_unit/config
      - ${ESSCONFIG_PATH}/instruments/tbl/efu/calib:/ess/ecdc/event_formation_unit/calib
    environment:
      - BROKER_TOPIC=staging_detector
      - FILE=tbl3he.json
      - CALIBRATION=tbl3henullcalib.json
      - KAFKA_CONFIG_PATH=/ess/ecdc/kafka-config-staging.json
      - BROKER_ADDR=10.102.80.36:8093
      - GRAPHITE=graphite
    restart: always
