# Copyright (C) 2016 European Spallation Source ERIC
#

testprogs = DetectorTest CSPECDataTest CSPECChanConvTest RingBufferTest CSPECEventTest

test: $(testprogs)
	echo "done building tests"

runtest: test
	for test in $(testprogs) ; do ./$$test --gtest_output=xml:$$test.xml ; done

CSPECChanConvTest: test/CSPECChanConvTest.cpp cspec/CSPECChanConv.cpp cspec/CSPECChanConv.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/CSPECChanConvTest.cpp cspec/CSPECChanConv.cpp -o $@ $(ldflags_test)

CSPECDataTest:  test/CSPECDataTest.cpp cspec/CSPECData.cpp cspec/CSPECChanConv.cpp cspec/CSPECData.h cspec/CSPECChanConv.h test/CSPECTestData.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/CSPECDataTest.cpp cspec/CSPECData.cpp cspec/CSPECChanConv.cpp -o $@ $(ldflags_test)

RingBufferTest: test/RingBufferTest.cpp common/RingBuffer.cpp common/RingBuffer.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/RingBufferTest.cpp common/RingBuffer.cpp  -o $@ $(ldflags_test)

DetectorTest: test/DetectorTest.cpp common/Detector.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/DetectorTest.cpp  -o $@ $(ldflags_test)

CSPECEventTest: test/CSPECEventTest.cpp cspec/CSPECEvent.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/CSPECEventTest.cpp  -o $@ $(ldflags_test)

coverage:
	gcov -r -b *.gcda
	lcov -c -d . --no-external -o lcov.out
	genhtml -o html lcov.out

valgrind: test
	rm -f valgrind_error
	for test in $(testprogs) ; do valgrind --leak-check=full -v --log-file="$$test.valgrind" ./$$test  || echo error >> valgrind_error; done
	test ! -e valgrind_error
