# Copyright (C) 2016 European Spallation Source ERIC
#

testprogs = testdetector testcspecdata testcspecchanconv testringbuffer testcspecevent

test: $(testprogs)
	echo "done building tests"

runtest: test
	for test in $(testprogs) ; do ./$$test --gtest_output=xml:$$test.xml ; done

testcspecchanconv: test/testCspecChanConv.cpp cspec/CSPECChanConv.cpp cspec/CSPECChanConv.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/testCspecChanConv.cpp cspec/CSPECChanConv.cpp -o $@ $(ldflags_test)

testcspecdata:  test/testCspecData.cpp cspec/CSPECData.cpp cspec/CSPECChanConv.cpp cspec/CSPECData.h cspec/CSPECChanConv.h test/CSPECTestData.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/testCspecData.cpp cspec/CSPECData.cpp cspec/CSPECChanConv.cpp -o $@ $(ldflags_test)

testringbuffer: test/testRingBuffer.cpp common/RingBuffer.cpp common/RingBuffer.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/testRingBuffer.cpp common/RingBuffer.cpp  -o $@ $(ldflags_test)

testdetector: test/testDetector.cpp common/Detector.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/testDetector.cpp  -o $@ $(ldflags_test)

testcspecevent: test/CSPECEventTest.cpp cspec/CSPECEvent.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/CSPECEventTest.cpp  -o $@ $(ldflags_test)

coverage:
	gcov -r -b *.gcda
	lcov -c -d . --no-external -o lcov.out
	genhtml -o html lcov.out

valgrind: test
	rm -f valgrind_error
	for test in $(testprogs) ; do valgrind --leak-check=full -v --log-file="$$test.valgrind" ./$$test  || echo error >> valgrind_error; done
	test ! -e valgrind_error

release: clean all clean test runtest
	echo Ready for checkin
