# Copyright (C) 2016 European Spallation Source ERIC
#

HDF5=
HDF5LIB= -L/usr/lib/x86_64-linux-gnu/hdf5/serial
ifdef HDF5

progs += gennmxfile

include+= -I../../h5cc/source

gennmxfile.src = nmxgen/nmxfile.cpp nmxgen/NMXArgs.cpp nmxgen/ReaderVMM.cpp NMX/Eventlet.cpp
gennmxfile.inc = nmxgen/NMXArgs.h nmxgen/ReaderVMM.h NMX/Eventlet.h
gennmxfile.obj = $(gennmxfile.src:%.cpp=%.o)

ldflags += -L../../h5cc/build -lh5cc $(HDF5LIB) -lhdf5_hl_cpp -lhdf5_cpp -lhdf5

gennmxfile: $(library) $(gennmxfile.obj) $(gennmxfile.inc)
	@echo building $@
	$(Q)$(cxx) $(gennmxfile.obj) $(library) $(ldflags) -o $@
endif
