# Copyright (C) 2016 European Spallation Source
#

cxx=g++

include  = -I. -I..
warnings = -Werror -Wall -Wpedantic -Wextra -Wmissing-include-dirs
optflags = -O3

ifdef NOKAFKA
kafkalibs=
else
kafkalibs= /usr/local/lib/librdkafka++.so /usr/local/lib/librdkafka.so
endif

cxxflags = -std=c++11 $(optflags)  $(include) $(warnings)

ldflags = -L/usr/local/lib -lpthread -lrt -ldl
ldflags.so = -Wl,--whole-archive $(library) $(kafkalibs) \
-Wl,--no-whole-archive -fPIC -shared

ifdef PROF
cxxflags += -pg
ldflags += -pg
ldflags.so += -pg
endif

ifdef NOKAFKA
cxxflags +=-DNOKAFKA
endif

ifdef COV
cxxflags += -coverage
endif

Q=@
ifdef V
Q=
endif
