# Copyright (C) 2016 European Spallation Source ERIC
#

HDF5=

ifdef HDF5

progs += gennmxfile

include+= -I../../h5cc/source -I/usr/include/hdf5/serial

gennmxfile.src = nmxgen/nmxfile.cpp nmxgen/NMXArgs.cpp nmxgen/ReaderVMM.cpp
gennmxfile.src += nmxgen/EventNMX.cpp nmxgen/ParserClusterer.cpp
gennmxfile.inc = nmxgen/NMXArgs.h nmxgen/ReaderVMM.h nmxgen/EventNMX.h
gennmxfile.inc += nmxgen/ParserClusterer.h
gennmxfile.obj = $(gennmxfile.src:%.cpp=%.o)

ifeq ($(_ARCH),Linux)
H5LIBPATH = -L/usr/lib/x86_64-linux-gnu/hdf5/serial
endif
ldflags = -L../../h5cc/build -lh5cc $H5LIBPATH -lhdf5_hl_cpp -lhdf5_cpp -lhdf5

gennmxfile: $(library) $(gennmxfile.obj) $(gennmxfile.inc)
	@echo building $@
	$(Q)$(cxx) $(gennmxfile.obj) $(library) $(ldflags) -o $@
endif
