# Copyright (C) 2016 European Spallation Source ERIC
#

cxx=g++

include  = -I. -I..
warnings = -Werror -Wall -Wpedantic -Wextra -Wmissing-include-dirs

# Experimental RELEASE flag - use  with caution
ifdef RELEASE
optflags = -DNDEBUG -m64 -Ofast -flto -march=native -O3
else
optflags = -O3
endif

# Experimental OPTIMIZE flag - use with caution
ifdef OPTIMIZE
optflags += -fprofile-use
endif

cxxflags = -std=c++11  $(optflags)  $(include) $(warnings)

ifdef NOKAFKA
kafkalibs=
else
kafkalibs= /usr/local/lib/librdkafka++.so /usr/local/lib/librdkafka.so
endif

ldflags = -L/usr/local/lib -lpthread -lrt -ldl
ldflags.so = -Wl,--whole-archive $(library) $(kafkalibs) \
-Wl,--no-whole-archive -fPIC -shared

ifdef PROF
cxxflags += -pg
ldflags += -pg
ldflags.so += -pg
endif

ifdef NOKAFKA
cxxflags +=-DNOKAFKA
endif

ifdef COV
cxxflags += -coverage -fprofile-generate
ldflags += -coverage -fprofile-generate
endif

Q=@
ifdef V
Q=
endif

ifndef GTEST
ldflags_test  = $(ldflags) -lgtest -pthread
cxxflags_test = $(cxxflags) -I/usr/include
else
ldflags_test  = $(ldflags) $(GTEST)/lib/libgtest.a -pthread
cxxflags_test = $(cxxflags) -I$(GTEST)/include -Wno-error=sign-compare
endif
