# Copyright (C) 2016 European Spallation Source
#

testprogs = testdetector testcspecdata testcspecchanconv testringbuffer

test: $(testprogs)
	echo "done building tests"

runtest: test
	for test in $(testprogs) ; do ./$$test --gtest_output=xml:$$test.xml ; done

testcspecchanconv: test/testCspecChanConv.cpp cspec/CSPECChanConv.cpp cspec/CSPECChanConv.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/testCspecChanConv.cpp cspec/CSPECChanConv.cpp -o $@ $(ldflags_test)

testcspecdata:  test/testCspecData.cpp cspec/CSPECData.cpp cspec/CSPECChanConv.cpp cspec/CSPECData.h cspec/CSPECChanConv.h test/CSPECTestData.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/testCspecData.cpp cspec/CSPECData.cpp cspec/CSPECChanConv.cpp -o $@ $(ldflags_test)

testringbuffer: test/testRingBuffer.cpp common/RingBuffer.cpp common/RingBuffer.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/testRingBuffer.cpp common/RingBuffer.cpp  -o $@ $(ldflags_test)

testdetector: test/testDetector.cpp common/Detector.h
	@echo building $@
	$(Q)g++ $(cxxflags_test) test/testDetector.cpp  -o $@ $(ldflags_test)

coverage:
	gcov *.gcda
	lcov -c -d . -o lcov.out
	genhtml -o html lcov.out
