{
 "title": "EFU",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instrument",
    "label": "instrument",
    "query": {}
   },
   {
    "name": "region",
    "label": "region",
    "query": {}
   },
   {
    "name": "serializer",
    "label": "serializer",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.receive.packets), 'packets/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.receive.dropped), 'dropped/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.receive.bytes), 'bytes/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.receive.fifo_seq_errors), 'fifo_seq err/s')"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "efu.$instrument.$region.main.uptime"
    }
   ]
  },
  {
   "title": "Input Thread Idle",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(asPercent(perSecond(efu.$instrument.$region.thread.input_idle), 10), 'ide/s')"
    },
    {
     "target": "alias(asPercent(perSecond(efu.$instrument.$region.thread.receive_idle), 10), 'ide/s')"
    }
   ]
  },
  {
   "title": "Processing Thread Idle",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(asPercent(perSecond(efu.$instrument.$region.thread.processing_idle), 18000), 'ide/s')"
    }
   ]
  },
  {
   "title": "Paring Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.parsing.readout_parsed), 'parsed readout/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parsing.errors.adc), 'adc err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parsing.errors.datalen), 'datalen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parsing.errors.fen), 'fen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parsing.errors.fiber), 'fiber err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parsing.errors.no_data), 'nodata err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parsing.errors.size), 'size err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parsing.errors.timefrac), 'time err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.parsing.errors.type), 'type err/s')"
    }
   ]
  },
  {
   "title": "Readout Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_amplitude), 'ampl err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_headersize), 'header size err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_datlen_invalid), 'datalen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_ringfen), 'datalen err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.tof_neg), 'tof neg/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.tof_high), 'tof high/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.error_datlen_mismatch), 'datalen missmatch/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.prevtof_high), 'pretof high/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.prevtof_neg), 'pretof neg/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.errors.no_serializer), 'serializer err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.errors.ring_mismatch), 'ring err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.errors.time), 'time err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.errors.type), 'type err/s')"
    }
   ]
  },
  {
   "title": "ESS Header",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.version.v0), 'header v0/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.version.v1), 'header v1/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors_buffer), 'buffer err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.buffer), 'buffer err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors_cookie), 'cookie err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.cookie), 'cookie err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors_header), 'header err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.header), 'header err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors_pad), 'pad err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.pad), 'pad err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors_seqno), 'deq err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.seqno), 'deq err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors_size), 'size err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.size), 'size err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors_version), 'version err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.version), 'version err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors_type), 'type err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.type), 'type err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors_timehigh), 'timehigh err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.timehigh), 'timehigh err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.essheader.errors.timefrac), 'timefrac err/s')"
    }
   ]
  },
  {
   "title": "Readouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.processed), 'readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.type.ibm_processed), 'ibm readout/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.type.ttl_proccessed), 'ttl readout/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.tof_count), 'tof/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.prevtof_count), 'pre tof/s')"
    }
   ]
  },
  {
   "title": "Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.tof_count), 'tof/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.prevtof_neg), 'pre tof neg/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.prevtof_count), 'pre tof/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.tof_neg), 'tof neg/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.errors.time), 'readout time err/s')"
    }
   ]
  },
  {
   "title": "Event Calculation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.ibm), 'ibm events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.events.ttl), 'ttl events/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.processed), 'readouts/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.type.ibm_processed), 'ibm readout/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.tof_count), 'tof/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.readouts.type.ttl_proccessed), 'ttl readout/s')"
    }
   ]
  },
  {
   "title": "Serialization and output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "alias(perSecond(efu.$instrument.$region.kafka.produce_bytes_ok), 'bytes ok/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.kafka.produce_bytes_error), 'bytes err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.kafka.err_unknown_topic), 'topic err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.kafka.err_queue_full), 'queue err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.kafka.produce_errors), 'produce err/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.kafka.produce_no_errors), 'produce ok/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_called), 'produce called/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_failed_no_reftime), 'prod no reftime/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_triggered_max_events), 'prod max events trig/s')"
    },
    {
     "target": "alias(perSecond(efu.$instrument.$region.serialize.$serializer.produce_triggered_reftime), 'prod reftime trig/s')"
    }
   ]
  }
 ]
}