# Copyright (C) 2016 European Spallation Source
#

cxx=g++


include  = -I. -I../libs/include -I../prototype2/cspec
warnings = -Werror -Wall -Wpedantic -Wextra -Wmissing-include-dirs
optflags = -O3
ldflags = -L/usr/local/lib -lrdkafka++ -lrdkafka -lpthread -lrt

ifdef KAFKA_ROOT
include += -I$(KAFKA_ROOT)/usr/include
ldflags += -L$(KAFKA_ROOT)/usr/lib64
endif

cxxflags = -std=c++11 $(optflags)  $(include) $(warnings)

ifdef PROF
prof = -pg
endif

ifdef COV
cxxflags += -coverage
endif
