# Copyright (C) 2016 European Spallation Source
#

testprogs = testdetector testcspecdata testcspecchanconv testbufferreader

test: $(testprogs)
	echo "done building tests"

runtest: test
	for test in $(testprogs) ; do ./$$test --gtest_output=xml:$$test.xml ; done

testcspecchanconv: test/testCspecChanConv.cpp cspec/CSPECChanConv.cpp cspec/CSPECChanConv.h
	@echo building $@
	$(Q)g++ $(cxxflags) $^ -o $@ $(ldflags) -lgtest -pthread

testcspecdata: test/testCspecData.cpp cspec/CSPECData.cpp cspec/CSPECData.h test/CSPECTestData.h
	@echo building $@
	$(Q)g++ $(cxxflags) $^ -o $@ $(ldflags) -lgtest -pthread

testbufferreader: test/testBufferReader.cpp BufferReader.cpp BufferReader.h
	@echo building $@
	$(Q)g++ $(cxxflags) $^ -o $@ $(ldflags) -lgtest -pthread

testdetector: test/testDetector.cpp Detector.h
	@echo building $@
	$(Q)g++ $(cxxflags) $^ -o $@ $(ldflags) -lgtest -pthread

coverage: runtest
	gcov *.gcda
	lcov -c -d . -o lcov.out
	genhtml -o html lcov.out
