#!/bin/bash

prog=iperf3
svrip="127.0.0.1"
svropt="-i 4 -s"
clnopt="-i 4 -n 102400M -c "$svrip

function launch()
{
   opt=$1
   log=$2
   while [[ 1 ]];
   do
      shift 2
      thread=$1
      port=$2
      if [[ $thread == "" ]]; then
         return
      fi
      echo "taskset -c $thread $prog -p $port $opt &> ${log}_${port}.txt&"
            taskset -c $thread $prog -p $port $opt &> ${log}_${port}.txt&
   done
}

function run_alt()
{
  rm -f *.txt
  killall iperf 2>/dev/null
  launch "$svropt" server_alt 12 5012 14 5014 16 5016 18 5018 20 5020 22 5022
  launch "$clnopt" client_alt 13 5012 15 5014 17 5016 19 5018 21 5020 23 5022
}


function run_seq()
{
  rm -f *.txt
  killall iperf 2>/dev/null
  launch "$svropt" server_seq 12 5012 13 5013 14 5014 18 5018 19 5019 20 5020
  launch "$clnopt" client_seq 15 5012 16 5013 17 5014 21 5018 22 5019 23 5020
}

function run_sep()
{
  rm -f *.txt
  killall iperf 2>/dev/null
  launch "$svropt" server_sep 12 5012 13 5013 14 5014 15 5015 16 5016 17 5017
  launch "$clnopt" client_sep 18 5012 19 5013 20 5014 21 5015 22 5016 23 5017
}

function run_loc()
{
  rm -f *.txt
  killall iperf 2>/dev/null
  launch "$svropt" server_loc 6 5006 7 5007 8 5008 9 5009 10 5010 11 5011
  launch "$clnopt" client_loc 18 5006 19 5007 20 5008 21 5009 22 5010 23 5011
}

run_alt
#run_seq
#run_sep
#run_loc

